### ISSUE TITLE
[HELP REQUIRED]

### ISSUE THREAD

**Issue by rajat-np** [vinzscam/react-native-file-viewer#2]
I have few doc files which I want to open. They are present in assets folder. Can you assist me in how to pass the filepath in the method FileViewer.open(filepath). 
Thank you.

**Comment by vinzscam** [comment]
Since the library works only with absolute paths and Android assets folder doesn't have any absolute path, we have to find a workaround.
A solution would be to copy the file from assets to a real folder. You can do this using [react-native-fs](https://github.com/itinance/react-native-fs).

Here is a snippet:

```
import RNFS from 'react-native-fs';
import FileViewer from 'react-native-file-viewer';

const file = 'file-to-open.doc'; // this is your file name
const dest = `${RNFS.DocumentDirectoryPath}/${file}`;
RNFS.copyFileAssets(file, dest)
.then(() => FileViewer.open(dest))
.then(() => {
   // success
})
.catch(_err => {
   /* */
});
```

**Comment by rajat-np** [comment]
@vinzscam Thanks.

**Comment by rajat-np** [comment]
I am getting this error while implementing the above snippet. 
Error: Asset '../../android/app/src/main/assets/Bible/48-Mark.doc' could not be opened
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:347)
    at MessageQueue.js:137
    at MessageQueue.__guard (MessageQueue.js:265)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:72

**Comment by rajat-np** [comment]
This is my code. 
`
import RNFS from 'react-native-fs';
const dataObjects = [ { title: '47-Matthew.doc' },
                      { title: '57-Philipians.doc' },
                      { title: '58-Colossians.doc' },
                      { title: '59-1-thessalonians.doc' },
                      { title: '60-2-thessalonians.doc' },
                      { title: '61-1-Timothy.doc' },
                      { title: '62-2-Timothy.doc' },
                      { title: '63-Titus.doc' },
                      { title: '73-Revelation.doc' }
                    ] // this is your file name

for ( var i = 0 ; i < dataObjects.length ; i++){
source = `../../android/app/src/main/assets/Bible/${dataObjects[i].title}`
dest = `${RNFS.DocumentDirectoryPath}/${dataObjects[i].title}`;
RNFS.copyFileAssets(source, dest)
.then(() => {
   console.log('copied')
})
.catch(err => {
console.log(err);
});
}
`

**Comment by rajat-np** [comment]
I think that react-native-fs does not accept relative path as well. I tried getting assets folder using RNFS.readDirAssets() but it shows some other files and folder , not the one which is under projects assets folder.

**Comment by rajat-np** [comment]
I am making an app which requires a screen to display some doc files. when a specific doc is pressed , it should open with the doc viewer app installed in the device.

**Comment by vinzscam** [comment]
`source` needs to be the relative path starting from the assets folder, like this:

```
source = `Bible/${dataObjects[i].title}`;
dest = `${RNFS.DocumentDirectoryPath}/${dataObjects[i].title}`;
```

Try it :)

**Comment by rajat-np** [comment]
thanks @vinzscam it worked. The file are now copied to the DocumentDirectoryPath. I have one doubt, these files are copied to my phone now, right ?

**Comment by vinzscam** [comment]
You're welcome @rajat-np. Yes, they are copied on your phone. You can even decide where the files have to be stored (app documents, app cache, etc) by changing the `react-native-fs` path constant.

You can read more here:
[react-native-fs path constants](https://github.com/itinance/react-native-fs#constants)
[Android FileProvider](https://developer.android.com/reference/android/support/v4/content/FileProvider.html)

**Comment by rajat-np** [comment]
So, finally I finished the last functionality of the app I was making, thanks a lot.

**Comment by Akashsystematix** [comment]
location of assets will be in src/res folder

**Comment by Smit12345** [comment]
how to open perticular folder of our local phone in react-native

**Comment by tragicmj** [comment]
const initPath =  'JharkhandUpdate1633700791252.pdf';
 const dest = `${RNFS.DocumentDirectoryPath}/JharkhandUpdate/JharkhandUpdateDocuments/${initPath}`;
        RNFS.copyFileAssets(initPath, dest)
        .then(() => FileViewer.open(dest))
        .then(() => {
          console.log("Done")
        })
        .catch(error => {
          console.log(error)
        });

The above is my code, I am trying to open pdf from this ' /data/user/0/com.fleapo.jharkhandupdate/files/JharkhandUpdate/JharkhandUpdateDocuments/JharkhandUpdate1633700791252.pdf' location but I am getting the below error.

[Error: Asset 'JharkhandUpdate1633700791252.pdf' could not be opened]

**Comment by omarbakr2020** [comment]
Hey Guys, I'm having the same issue, Could you help me resolve it?

I have the functionality to download (or copy) an image from my src/assets/cards folder to the device's directory, Could you guys help me with that

I want to copy an image called (11.jpg) into my device's storage in both android & iOS. But I can't do it. Could you help me?

Thank you

**Comment by eliasg52** [comment]
i have the same issue. I cant open files for use in a function. I have the error: [Error: Asset 'cat.jpg' could not be opened]. My code is this: 

```
export function getAssetPath(fileName: string): string {
  if (Platform.OS === 'android') {
    return `/assets/${fileName}`;
  }
  return `${MainBundlePath}/${fileName}`;
}

export async function getAbsolutePath(filePath: string): Promise<string> {
  if (Platform.OS === 'android') {
    if (filePath.startsWith('/assets/')) {
      // const fileName = filePath;
      const fileName = filePath.replace('/assets/', '');
      const destPath = `${ExternalCachesDirectoryPath}/${fileName}`;
      console.log('despatch', destPath);
      if (!(await exists(destPath))) {
        await RNFS.copyFileAssets(fileName, destPath);
      }

      return destPath;
    }
  }
  return filePath;
}

 const [filePath, setFilePath] = useState(getAssetPath('cat.jpg'));

  getAbsolutePath(filePath)
    .then(path => {
      console.log('path:', path);
      ImageTools.GetImageRGBAs(path)
        .then((value: any) => {
          console.log('value:', value);
        })
        .catch((error: any) => console.log('error:', error)); 
    })
    .catch(err => console.log(err));
```

i cant reach the line  console.log('path:', path); 
I tried putting the assets folder in many places without any success. please help me this is driving me crazy

**Comment by omarbakr2020** [comment]
Hey @eliasg52 

I've got this issue before and it drove me crazy. I spent over 2 weeks trying to find a solution for it, and I DID. I'll try to list the same steps I followed in order to get that issue resolved. That might help you.

For my issue, I wanted to read local file assets (images) from the android folder or IOS so I can copy them to the Downloads or Documents folder in the device's directory. Apparently, I needed to copy them manually inside the android folder (For Android) and iOS folder (For iOS).

I wanted to move my assets (the images) into android/app/src/main/res/drawable (For Android) , and here are the steps I followed to achieve that

1. Open your Android Studio project and navigate to the res folder.
2. Inside the res folder, create a new folder called drawable if it doesn't exist already.
3. Copy the image you want to use into the drawable folder.
4. Rename the image file if necessary to ensure it doesn't contain any spaces or special characters. For example, if your image is named "image 1.jpg", rename it to "image_1.jpg".
5. Now you can use the copyFileRes function provided by react-native-fs to copy the image to another location within your app.

If you are still getting the error message "Res 'image_1.jpg' could not be opened" when trying to access the image, make sure that the image is in the correct format (e.g. JPEG or PNG) and that the file name is spelled correctly and matches the exact file name in the drawable folder (including capitalization). If the issue persists, try restarting your development server and/or cleaning your project in Android Studio to rebuild any cached resources.

For iOS:

1. Open your Xcode project and navigate to the project navigator on the left-hand side of the screen.
2. Right-click on the folder where you want to add the image (e.g. Assets.xcassets for image assets).
3. Select "New Image Set" from the context menu.
4. Give the image set a name that describes the image (e.g. "MyImage").
5. Drag and drop the image you want to use into the image well in the middle of the screen.
6. Adjust the properties of the image set as necessary, such as specifying a different size class for different device types or adding image variants for different display scales.
7. Save the changes to the project.

I copied them manually from my assets folder (Drag and Drop) to the destination folder (drawable or Assets.xcassets)

If you encountered any issues or problems, try different workarounds, but that should solve your problem at least temporarily

**Comment by flyskywhy** [comment]
@rajat-np @vinzscam @Akashsystematix @SmitVavliya @tragicmj @omarbakr2020 @eliasg52 , I just create [react-native-get-asset](https://github.com/flyskywhy/react-native-get-asset) which described how to bundle asset automatically at bundle time, and one function to copy asset to file system or read asset as base64 data url on Android, iOS and Web at debug or release run time. :stuck_out_tongue:

**Comment by eliasg52** [comment]
hi @flyskywhy  how are you? im trying to use the library but i cant, i need to acces for example to image in bundle asset  in the same directory as my function, how i can reach this?

**Comment by flyskywhy** [comment]
> i have the same issue. I cant open files for use in a function. I have the error: [Error: Asset 'cat.jpg' could not be opened]. My code is this:
> 
> ```
> export function getAssetPath(fileName: string): string {
>   if (Platform.OS === 'android') {
>     return `/assets/${fileName}`;
>   }
>   return `${MainBundlePath}/${fileName}`;
> }
> 
> export async function getAbsolutePath(filePath: string): Promise<string> {
>   if (Platform.OS === 'android') {
>     if (filePath.startsWith('/assets/')) {
>       // const fileName = filePath;
>       const fileName = filePath.replace('/assets/', '');
>       const destPath = `${ExternalCachesDirectoryPath}/${fileName}`;
>       console.log('despatch', destPath);
>       if (!(await exists(destPath))) {
>         await RNFS.copyFileAssets(fileName, destPath);
>       }
> 
>       return destPath;
>     }
>   }
>   return filePath;
> }
> 
>  const [filePath, setFilePath] = useState(getAssetPath('cat.jpg'));
> 
>   getAbsolutePath(filePath)
>     .then(path => {
>       console.log('path:', path);
>       ImageTools.GetImageRGBAs(path)
>         .then((value: any) => {
>           console.log('value:', value);
>         })
>         .catch((error: any) => console.log('error:', error)); 
>     })
>     .catch(err => console.log(err));
> ```
> 
> i cant reach the line console.log('path:', path); I tried putting the assets folder in many places without any success. please help me this is driving me crazy


Please move your 'cat.jpg' as `YOUR_APP/public/cat.jpg`, use below code, and tell me the result.
```
import GetAsset from 'react-native-get-asset';

const CAT_JPG_URL =
  Platform.OS !== 'web' ? require('../../public/cat.jpg') : 'cat.jpg';

export async function getAbsolutePath(
  src: string,
  fileName: string,
): Promise<string> {
  return await GetAsset.downloadUrlOrRequireId2Storage({
    src,
    dst:
      Platform.OS !== 'web' &&
      Platform.select({
        android: `${RNFS.ExternalDirectoryPath}/${fileName}`,
        ios: `${RNFS.DocumentDirectoryPath}/${fileName}`,
      }),
    iosReleaseRequireIdAvoidCopy: true,
  });
}

...

  getAbsolutePath(CAT_JPG_URL, 'cat.jpg')
    .then(path => {
      console.log('path:', path);
      ImageTools.GetImageRGBAs(path)
        .then((value: any) => {
          console.log('value:', value);
        })
        .catch((error: any) => console.log('error:', error)); 
    })
    .catch(err => console.log(err));
```

**Comment by wazirkhan786** [comment]
Import {Image} from 'react-native


const ImageUri= Image.resolveAssetSource(Images.signaturePadIcon).uri

then use this Uri to download the file or anything else
