### ISSUE TITLE
Callback/listener for when viewer is dismissed

### ISSUE THREAD

**Issue by timt** [vinzscam/react-native-file-viewer#28]
Hi, great library. 

We need to be able to detect when the user has dismissed the file viewer. Would it be possible to add a callback/listener that we can use to detect when that happens and the control returns to the main app?

**Comment by vinzscam** [comment]
Hi @timt, sure. I will try to implement it as soon as possible

**Comment by JeremyBradshaw7** [comment]
This is a requirement for us too, because we're downloading via RNFS to a temporary location and want to clean up that file when the user closes the view. We were closing after a timeout (the viewer doesn't seem to care if this happens while being viewed), but now we want to offer the user a chance to save/copy from the viewer, and that only works while the file exists, so removal after dismissal is the only way to do this cleanly.

**Comment by vinzscam** [comment]
Hi,
This feature is now implemented starting from version `1.0.12`.

Here an example:
```
FileViewer.open(path, {
  onDismiss: () => console.log('view dismissed!')
});
```

**Comment by diego-lipinski-de-castro** [comment]
![image](https://user-images.githubusercontent.com/29608698/52285300-3af70a80-294d-11e9-8f2a-e91c310165f2.png)

FileViewer 1.0.13
ReactNative 0.56.0

**Comment by pablodance** [comment]
Hi,

I'm also trying to implement an ondismis as I want to show a loader whilst pulling in a document 

NFS.downloadFile(options).promise
      .then(this.setState({
        visible: !this.state.visible,
      }))
      .then(() => FileViewer.open(
        localFile,
        {
          onDismiss: () => console.warn('view dismissed!')
        }
      ))
      .then(() => {

      })
      .catch(error => {
        // error
      });

above isnt firing for me

**Comment by vinzscam** [comment]
Hi @pablodance,
could you please share more details about the devices or simulator you're using?
