### ISSUE TITLE
Typescript definitions incorrect

### ISSUE THREAD

**Issue by maddijoyce** [vinzscam/react-native-file-viewer#6]
Hey @vinzscam,

It looks like you changed the typescript definitions to remove the default tag, but the default tag is still in the index.js file?

Cheers,
Maddi

**Comment by vinzscam** [comment]
Hi @maddijoyce!
yes, the declaration is correct. The definition match perfectly the implementation.
If I apply your changes I get an error. This because since Typescript 2.6 it is possible to use `export default` in declarations only for exporting strings and numeric literals as you can see here: [Arbitrary expressions are forbidden in export assignments in ambient contexts](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#arbitrary-expressions-are-forbidden-in-export-assignments-in-ambient-contexts). Probably you're on an older version of typescript but everything should run smoothly anyway.
Do you have any particular issue using the library? It should be fine to import the library using one of the following ways:

```
import FileViewer from 'react-native-file-viewer';
// or
import * as FileViewer from 'react-native-file-viewer';
// or
import { open } from 'react-native-file-viewer';
```
