### ISSUE TITLE
Jetifier and react-native-file-viewer

### ISSUE THREAD

**Issue by sm2017** [vinzscam/react-native-file-viewer#78]
I am using react-native-file-viewer@2.0.2 , AFAIK it migrated to Android X , my react native version is 0.62.2 and in gradle.properties I have

```
android.useAndroidX=true
android.enableJetifier=true
```

I package.json I have `postinstall` script `"postinstall": "jetifier"` 

After installing react-native-file-viewer and running jetifier , it convert your code to android support 

![image](https://user-images.githubusercontent.com/19644997/80561812-f7c60300-89fa-11ea-98bb-04ab00cdd287.png)

If I remove jetifier from postinstall , your code is androidx but I have some android support modules and have to enable jetifier

I am using jetifier@1.6.5

**Comment by vinzscam** [comment]
Hi! Jetifier shouldn't touch that import. I believe that your code is breaking because you are using the `preBuild.doFirst` in your build.gradle as described [here](https://github.com/vinzscam/react-native-file-viewer#android-x-breaking-changes). Please remember to remove the snippet from your code, since it is only required for RN < 0.60.
